//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEstMB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявки()
        {
            this.Комментарии = new HashSet<Комментарии>();
        }
    
        public int ID_Заявки { get; set; }
        public Nullable<System.DateTime> Дата_добавления { get; set; }
        public string Вид_оргтехники { get; set; }
        public string Модель { get; set; }
        public string Описание_проблемы { get; set; }
        public string Статус_заявки { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public Nullable<int> FK_Запчасти { get; set; }
        public Nullable<int> FK_Мастера { get; set; }
        public Nullable<int> FK_Заказчика { get; set; }
    
        public virtual Запчасти Запчасти { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Комментарии> Комментарии { get; set; }
    }
}
