//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEstMB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комментарии
    {
        public int ID_Комментария { get; set; }
        public string Комментарий { get; set; }
        public Nullable<int> FK_Мастера { get; set; }
        public Nullable<int> FK_Заявки { get; set; }
    
        public virtual Заявки Заявки { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
